### ISSUE TITLE
[Bug] Fabric 1.0.2 for 1.20 incorrectly marked as supporting 1.20.4

### ISSUE THREAD

**Issue by Linguardium** [SuperMartijn642/Formations#6]
**Version Info**
- Minecraft, 1.20.4
- Formations, https://www.curseforge.com/minecraft/mc-mods/formations/files/4862075

**What mod loader are you using?**: Fabric/Forge/NeoForge/Quilt
Fabric

**Description of the Bug**
Title

**Steps to Reproduce**
Download mod,  load into world, break log

**Screenshots**
N/A

**Log**
https://mclo.gs/VvGlVAw

**Comment by SuperMartijn642** [comment]
There is already a newer file specifically for 1.20.4 which fixed the crash you attached.

**Comment by Linguardium** [comment]
yes, this bug is specifically pointing out that the file is marked incorrectly and linked to the file that was incorrectly marked. ideally you would go and fix the incorrect tagging of the file

**Comment by SuperMartijn642** [comment]
I don't see why I would unmark previous versions whenever I fix something. Of course mods will have bugs, that's why I fixed it and released an update

**Comment by Linguardium** [comment]
because you incorrectly marked it as supported and then didnt change the version when posting a new patch version. so you now have 2 different 1.0.2 versions that "support" 1.20.4, one of which obviously doesnt. it creates confusion, may cause issues with some launchers, and ultimately is incorrect

**Comment by SuperMartijn642** [comment]
> because you incorrectly marked it as supported and then didnt change the version when posting a new patch version.

That's not the case, I intentionally marked the file for 1.20.4. It then turned out there was a crash with Minecraft 1.20.4 and I released an update specifically for that version. I don't see why I would unmark previous updates when releasing a new version.

> so you now have 2 different 1.0.2 versions that "support" 1.20.4

Ah I see how that can be confusing. I did not realize both files had the same version number.

The 1.0.2-1.20 files for both Fabric and Forge are now no longer marked for 1.20.4 on CurseForge and Modrinth.
Thank you for reporting the issue!
